# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing

on:
  push:
    branches: [ NET-0031 ]
  pull_request:
    branches: [ NET-0031 ]

env:
  node-version: "14.x"

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.node-version }}
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: yarn
    - name: Run ESLint
      run: yarn run eslint -o reports/lint-test-results.xml
    - run: find ~ -name "lint-test-results.xml"
    - name: Archive lint results
      uses: actions/upload-artifact@v2
      with:
        name: lint-test-results
        path: reports/